-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 08:41:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  `fone` VARCHAR(45) NULL,
  `senha` VARCHAR(155) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `dataPedido` varchar(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_usuarios_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ecommerce`.`usuarios` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `descricao` TEXT NOT NULL,
  `imagem` VARCHAR(500) NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `nome` VARCHAR(155) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `imagem` TEXT NOT NULL,
  `status` CHAR(1) NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_categoria_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `ecommerce`.`categorias` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`itensPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`itensPedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itens_pedido_pedido_idx` (`idPedido` ASC) VISIBLE,
  INDEX `fk_itens_pedido_produto_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_itens_pedido_pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `ecommerce`.`pedidos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_pedido_produto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `ecommerce`.`produtos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(145) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(145) NOT NULL,
  `cidade` VARCHAR(145) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cep` VARCHAR(12) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  `idUsuario` INT NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ecommerce`.`usuarios` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`configLoja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`configLoja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeFantasia` VARCHAR(145) NOT NULL,
  `endCompleto` VARCHAR(145) NOT NULL,
  `email` VARCHAR(145) NOT NULL,
  `fone` VARCHAR(45) NOT NULL,
  `instagram` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `logotipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
